version: '3'
services:
  app:
    build: .
    depends_on:
      - redis
      - rabbitmq
      - mysql
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
